Name=input("Enter Your Name :")
Roll=input("Enter Your Roll :")
University =input("Enter Your University Name :")
Phone=input("Enter Your Phone Number :")
Cgpa=input("Enter Your CGPA :")
print("Student Information  :")
print("-----------------------")
print("Name :  "+Name)
print("Roll :  "+Roll)
print("Class : "+University)
print("Phone :"+Phone)
print("CGPA  : "+Cgpa)